<?php

namespace MagasinBundle\Repository;

/**
 * SlideshowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlideshowRepository extends \Doctrine\ORM\EntityRepository
{
}
