MagasinBundle\Entity\Livreur:
    type: entity
    table: null
    repositoryClass: MagasinBundle\Repository\LivreurRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        adresse:
            type: string
            length: 255
        password:
            type: string
            length: 255
        lat:
            type: string
            length: 255
        lon:
            type: string
            length: 255
        tel:
            type: string
            length: 255
    lifecycleCallbacks: {  }
